# Deploy preview channels on pull requests

name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install public-site dependencies
        run: npm ci
        working-directory: public-site

      - name: Build public-site
        run: npm run build
        working-directory: public-site

      - name: Install studio-site dependencies
        run: npm ci
        working-directory: studio-site

      - name: Build studio-site
        run: npm run build
        working-directory: studio-site

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RMCWEBSITE_1AD84 }}
          projectId: rmcwebsite-1ad84
